name: qa4sm_reader
channels:
    - defaults
    - conda-forge
dependencies:
    - xarray=0.21.1 # specify version that handles string data variables on Windows
    - netcdf4=1.6.4 # specify version
    - pandas
    - numpy
    - matplotlib
    - cartopy>=0.21
    - pyproj
    - h5netcdf
    - hdf5=1.12.2 # specify version
    - pip
    - pip:
          - parse
          - colorcet
          - scipy
          - seaborn
          - pygeogrids
          - pytest
          - pytest-cov
